default:
  tags:
    - gab
variables:
  VAULT_TOKEN: ""
  VAULT_ADDR: http://vault.vault.svc.cluster.local:8200

stages:
  - auth
  - run

vault:
  stage: auth
  image: hashicorp/vault
  script:
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=ansible jwt=$CI_JOB_JWT)"
    - vault kv get -field=fake_ansible_ssh_key kv/ansible > ssh_key
  artifacts:
    paths:
      - ssh_key
    expire_in: 1 minute

run:
  stage: run
  image: willhallonline/ansible:alpine
  script:
    - mkdir ~/.ssh
    - cp ssh_key ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
    - cat 
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook -i inventory/luna base.yml
