default:
  tags:
    - gab

variables:
  VAULT_ADDR: http://vault.vault.svc.cluster.local:8200

stages:
  - auth
  - run

vault:
  stage: auth
  image: hashicorp/vault
  script:
    - vault write -field=token auth/jwt/login role=ansible jwt=$CI_JOB_JWT > token
    - export VAULT_TOKEN=$(cat token) && vault kv get -field=ansible_ssh_key kv/ansible > ssh_key
  artifacts:
    paths:
      - ssh_key
      - token
    expire_in: 1 minute

run:
  stage: run
  image: willhallonline/ansible:alpine
  script:
    - mkdir ~/.ssh
    - cp ssh_key ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
    - eval `ssh-agent`
    - ssh-add
    - ssh-add -l
    - export VAULT_TOKEN=$(cat token)
    - |
        cat << EOF > ~/.ansible.cfg
        [defaults]
        host_key_checking = False

        [ssh_connection]
        ssh_args = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s
        EOF
    - pip install hvac
    - ansible-playbook -i inventory/luna base.yml
