default:
  tags:
    - gab
variables:
  VAULT_TOKEN: ""
  VAULT_ADDR: http://vault.vault.svc.cluster.local:8200
  SSH_KEY: ""

stages:
  - auth
  - run

vault:
  stage: auth
  image: hashicorp/vault
  script:
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=ansible jwt=$CI_JOB_JWT)"
    - SSH_KEY=$(vault kv get -field=ansible_ssh_key kv/ansible)

run:
  stage: run
  image: ansible/ansible
  script:
    - mkdir ~/.ssh
    - echo $SSH_KEY > ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
    - ansible-playbook -i inventory/luna base.yml
