default:
    tags:
        - gab
stages:
  - auth
  - run

variables:
  VAULT_TOKEN: ""
  VAULT_ADDR: http://vault.vault.svc.cluster.local:8200
  SSH_KEY: ""

vault:
  stage: auth
  image: hashicorp/vault
  script:
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=ansible jwt=$CI_JOB_JWT)"
    - $SSH_KEY=$(vault kv get -field=ansible_ssh_key kv/ansible)

run:
  stage: run
  image: ansible/ansible
