---
- hosts: vms
  strategy: free
  gather_facts: false
  tasks:
  - name: Kill running yum
    shell: "kill -9 $(ps -ef | grep -v grep | grep -w yum | awk '{print $2}')"
    ignore_errors: yes
  - name: upgrade all packages
    yum: 
      name: "*"
      state: latest
      exclude:
        - kubectl
        - kubeadm
        - kubelet
        - kubernetes-cni
      disable_gpg_check: true