---
- name: Grafana repo
  ansible.builtin.copy:
    src: grafana.repo
    dest: '/etc/yum.repos.d/grafana.repo'

- name: Install agent
  yum:
    state: installed
    name: "grafana-agent"

- name: Install base config
  notify: restart
  ansible.builtin.template:
    src: grafana-agent.yaml.j2
    dest: '/etc/grafana-agent.yaml'

- name: Setup agent env file
  notify: restart
  ansible.builtin.copy:
    src: grafana-agent
    dest: '/etc/sysconfig/grafana-agent'

- name: Setup agent service
  ansible.builtin.file:
    owner: root
    group: root
    mode: 0755
    path: /etc/systemd/system/grafana-agent.service.d
    state: directory

- name: Set up grafana.service override
  notify: restart
  ini_file:
    dest: /etc/systemd/system/grafana-agent.service.d/override.conf
    owner: root
    group: root
    mode: 0644
    section: Service
    option: User
    value: root

- name: Start agent
  ansible.builtin.systemd_service:
    state: stopped
    enabled: false
    daemon_reload: true
    name: grafana-agent
