k8s_packages:
  - kubeadm-1.28.2
  - kubelet-1.28.2
  - nfs-utils
  - iscsi-initiator-utils

docker_compose_install: false
is_kubernetes: true

kubernetes_sysctl: {
    "vm.max_map_count":"262144",
    "net.ipv4.ip_local_port_range": 1024 65000,
    "net.ipv4.tcp_fin_timeout":"30",
    "net.core.somaxconn":"1024",
    "net.core.netdev_max_backlog":"2000",
    "net.ipv4.tcp_max_syn_backlog":"2048",
    "vm.overcommit_memory":"1",
    "net.bridge.bridge-nf-call-iptables":"1",
    "fs.may_detach_mounts":"1"
}