---

- name: Download node_exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract node_exporter
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/

- name: Copy node exporter
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/sbin/
    mode: '0755'

- name: Create a node_exporter directory
  ansible.builtin.file:
    path: /etc/node_exporter
    state: directory
    mode: '0755'

- name: Create node_exporter systemd service file
  template:
    src: templates/node_exporter.service.j2
    dest: /lib/systemd/system/node_exporter.service

- name: Start node_exporter
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    daemon_reload: true
    name: node_exporter