---

- name: Create directories if needed
  ansible.builtin.file:
    path: "{{ item.value.dest }}"
    state: directory
  loop: "{{ mounts | dict2items }}"

- name: Mount needed network shares
  ansible.posix.mount:
    path: "{{ item.value.dest }}"
    src: "{{ item.value.source }}"
    fstype: cifs
    state: mounted
    opts: 'defaults,nofail,_netdev,noperm,username=mount,password=mount'
  loop: "{{ mounts | dict2items }}"

