---
- name: Add Kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes YUM repo
    baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
    gpgkey: 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'

- name: Install kubernetes packages
  yum:
    state: installed
    name: "{{ k8s_packages }}"
    disable_gpg_check: true

- name: Add the netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set sysctl values
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ kubernetes_sysctl | dict2items }}"

- name: Ensure Docker is stopped and disabled.
  systemd:
    daemon_reload: true
    name: docker
    state: stopped
    enabled: false