- name: Add yum repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    metalink: "https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch"
    gpgkey: "http://mirror.its.dal.ca/pub/epel/RPM-GPG-KEY-EPEL-7"

- name: Install common packages
  yum:
    state: installed
    name: "{{ packages }}"

- name: Disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: true

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Grab ohmyzsh repo
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: '/root/.oh-my-zsh'

- name: Copy server configs repo
  git:
    repo: 'git@github.com:Gabisonfire/server-configs.git'
    accept_hostkey: true
    dest: '/etc/server-configs'

- name: Copy zshrc
  ansible.builtin.copy:
    src: zsh_config
    dest: '/root/.zshrc'

- name: Create ssh directory if it does not exist
  ansible.builtin.file:
    path: '/root/.ssh'
    state: directory

- name: Copy authorized keys
  ansible.builtin.copy:
    src: authorized_keys
    dest: '/root/.ssh/authorized_keys'

- name: Setup root account
  user:
    name: root
    shell: '/bin/zsh'
    password: "{{root_password}}"

- name: Copy root CA
  ansible.builtin.copy:
    src: luna.crt
    dest: '/etc/pki/ca-trust/source/anchors/luna.crt'
  notify: update-ca-store

- name: Remove gab repository
  yum_repository:
    name: gab-repo
    state: absent

- name: Remove old configs directory
  ansible.builtin.file:
    state: absent
    path: /etc/configs/

- name: Remove old configs directory
  ansible.builtin.file:
    state: absent
    path: /root/server-configs/
