- name: Install epel repo
  yum:
    state: installed
    name: epel-release
  when: ansible_os_family == "RedHat"

- name: Install common packages
  yum:
    state: installed
    name: "{{ packages }}"
  when: ansible_os_family == "RedHat"

- name: Disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: true

- name: Enable Chrony
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: true

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Grab ohmyzsh repo
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: '/root/.oh-my-zsh'

- name: Copy zshrc
  ansible.builtin.copy:
    src: zsh_config
    dest: '/root/.zshrc'

- name: Create ssh directory if it does not exist
  ansible.builtin.file:
    path: '/root/.ssh'
    state: directory

- name: Copy authorized keys
  ansible.builtin.copy:
    src: authorized_keys
    dest: '/root/.ssh/authorized_keys'

- name: Setup root account
  user:
    name: root
    shell: '/bin/zsh'
    password: "{{root_password}}"

- name: Copy root CA
  ansible.builtin.copy:
    src: luna.crt
    dest: '/etc/pki/ca-trust/source/anchors/luna.crt'
  notify: update-ca-store

- name: Cron to backup crons
  ansible.builtin.cron:
    name: "save crons"
    minute: "0"
    hour: "2"
    job: "crontab -l > /mnt/backups/cron/$(hostname)"