---
mount: cifs

cifs_mounts:
  torrents:
    source: //gab-data-10gb-metal.luna.net/Torrents
    dest: /mnt/torrents
  series:
    source: //gab-data-10gb-metal.luna.net/series
    dest: /mnt/series
  movies:
    source: //gab-data-10gb-metal.luna.net/movies
    dest: /mnt/movies
  backups:
    source: //gab-data-10gb-metal.luna.net/Backups
    dest: /mnt/backups
  minio:
    source: //gab-data-10gb-metal.luna.net/Minio
    dest: /mnt/minio
  docs:
    source: //gab-data-10gb-metal.luna.net/Docs
    dest: /mnt/docs
  media:
    source: //gab-data-10gb-metal.luna.net/Media
    dest: /mnt/media

kopia:
  docs:
    description: "Backup of /mnt/docs"
    path: "/mnt/docs"
    time_string: "Mon *-*-* 01:00:00"
  backups:
    description: "Backup of /mnt/backups"
    path: "/mnt/backups"
    time_string: "Mon *-*-* 01:00:00"
  velero:
    description: "Backup of /mnt/minio/velero"
    path: "/mnt/minio/velero"
    time_string: "Fri *-*-* 01:00:00"
