---
mount: cifs

cifs_mounts:
  torrents:
    source: //gab-data-10gb-proxmox.luna.net/Torrents
    dest: /mnt/torrents
  series:
    source: //gab-data-10gb-proxmox.luna.net/series
    dest: /mnt/series
  movies:
    source: //gab-data-10gb-proxmox.luna.net/movies
    dest: /mnt/movies
  backups:
    source: //gab-data-10gb-proxmox.luna.net/Backups
    dest: /mnt/backups
  minio:
    source: //gab-data-10gb-proxmox.luna.net/Minio
    dest: /mnt/minio
  data:
    source: //gab-data-10gb-proxmox.luna.net/Z
    dest: /mnt/data
  media:
    source: //gab-data-10gb-proxmox.luna.net/Media
    dest: /mnt/media
